import type { Compound } from '../../src/chemistry/compounds/types.js';
import { FORMULA_TO_SMILES } from '../../src/engine/parser/formula-map.js';
import { formulaToHillKey, parseFormula } from '../../src/engine/parser/formula.js';

export interface FormulaMapEntry {
  readonly smiles: string;
  readonly cid: number;
  readonly priority: number;
}

export function buildFormulaMapGenerated(
  compounds: ReadonlyArray<Compound>,
): Map<string, FormulaMapEntry> {
  // Group by Hill key, keep the best (lowest priority, then lowest cid)
  const map = new Map<string, FormulaMapEntry>();

  for (const compound of compounds) {
    if (compound.cid === null) continue;

    const parsed = parseFormula(compound.molecularFormula);
    if (!parsed.ok) continue;

    const hillKey = formulaToHillKey(parsed.value);

    // Skip keys already in the manual map (§6.8: manual always wins)
    if (Object.prototype.hasOwnProperty.call(FORMULA_TO_SMILES, hillKey)) continue;

    const existing = map.get(hillKey);
    const better =
      !existing ||
      compound.priority < existing.priority ||
      (compound.priority === existing.priority && compound.cid < existing.cid);

    if (better) {
      map.set(hillKey, { smiles: compound.smiles, cid: compound.cid, priority: compound.priority });
    }
  }

  return map;
}

export function serializeFormulaMapGenerated(
  map: ReadonlyMap<string, FormulaMapEntry>,
  generatedAt: string,
): string {
  const lines: string[] = [
    `// Generated by scripts/pubchem-fetch at ${generatedAt}`,
    `// DO NOT EDIT MANUALLY — regenerate with: pnpm run fetch-compounds`,
    ``,
    `export const FORMULA_MAP_GENERATED: ReadonlyMap<string, { readonly smiles: string; readonly cid: number; readonly priority: number }> =`,
    `  new Map([`,
  ];

  const sorted = [...map.entries()].sort((a, b) => a[0].localeCompare(b[0]));
  for (const [key, entry] of sorted) {
    lines.push(
      `    [${JSON.stringify(key)}, { smiles: ${JSON.stringify(entry.smiles)}, cid: ${entry.cid}, priority: ${entry.priority} }],`,
    );
  }

  lines.push(`  ]);`);
  return lines.join('\n') + '\n';
}
