// Generated by scripts/pubchem-fetch at 2026-05-06T00:00:00Z
// DO NOT EDIT MANUALLY — regenerate with: pnpm run fetch-compounds

export const FORMULA_MAP_GENERATED: ReadonlyMap<
  string,
  { readonly smiles: string; readonly cid: number; readonly priority: number }
> = new Map([
  ['C6H12O6', { smiles: 'OC[C@H]1OC(O)[C@H](O)[C@@H](O)[C@@H]1O', cid: 5793, priority: 20 }],
  ['C2H4O2', { smiles: 'CC(=O)O', cid: 176, priority: 5 }],
  ['C3H8O', { smiles: 'CCCO', cid: 1031, priority: 50 }],
  ['C4H10O', { smiles: 'CCCCO', cid: 6524, priority: 60 }],
  ['C6H5OH', { smiles: 'Oc1ccccc1', cid: 996, priority: 40 }],
  ['C7H8', { smiles: 'Cc1ccccc1', cid: 1140, priority: 30 }],
  ['C10H8', { smiles: 'c1ccc2ccccc2c1', cid: 931, priority: 35 }],
  ['C5H5N', { smiles: 'c1ccncc1', cid: 1049, priority: 50 }],
  ['C4H5N', { smiles: 'c1cc[nH]c1', cid: 749, priority: 55 }],
  ['C9H8O4', { smiles: 'CC(=O)Oc1ccccc1C(=O)O', cid: 2244, priority: 10 }],
]);
